package com.manet.backend.entity;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

@Entity
@Table(name = "ai_decisions")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AIDecision {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * AI decision taken after prediction
     * Example:
     * REROUTE
     * ISOLATE_NODE
     * RESTART_SERVICE
     * ROLLBACK_CONFIGURATION
     * NOTIFY_OPERATOR
     * NO_ACTION
     */
    @Column(nullable = false, length = 100)
    private String decision;

    /**
     * Confidence score (0 - 100)
     */
    @Column(nullable = false)
    private Double confidence;

    /**
     * Recoverability score (0 - 100)
     */
    @Column(nullable = false)
    private Double recoverabilityScore;

    /**
     * Action recommended by AI
     */
    @Column(nullable = false, length = 150)
    private String recommendedAction;

    /**
     * Action actually executed
     */
    @Column(length = 150)
    private String actualAction;

    /**
     * Additional remarks generated by AI
     */
    @Column(columnDefinition = "TEXT")
    private String remarks;

    /**
     * Decision timestamp
     */
    @Column(nullable = false)
    private LocalDateTime decisionTime;

    /**
     * AI Model Used
     * Example:
     * Random Forest
     * XGBoost
     * LSTM
     */
    @Column(length = 100)
    private String modelName;

    /**
     * Link to Prediction record
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "prediction_id", nullable = false)
    private Prediction prediction;

    @PrePersist
    public void prePersist() {
        this.decisionTime = LocalDateTime.now();
    }
}