package com.manet.backend.simulation.fault;

public enum FaultScenario {

    NONE,

    NODE_FAILURE_SCENARIO,

    LINK_FAILURE_SCENARIO,

    BATTERY_DEGRADATION_SCENARIO,

    CPU_OVERLOAD_SCENARIO,

    PACKET_LOSS_SCENARIO,

    HIGH_LATENCY_SCENARIO,

    NETWORK_CONGESTION_SCENARIO,

    RADIO_INTERFERENCE_SCENARIO,

    ROUTE_FAILURE_SCENARIO,

    NETWORK_PARTITION_SCENARIO,

    MULTI_FAULT_SCENARIO
}